#ifndef TRACKEE_BOX_H
#define TRACKEE_BOX_H

#include <string>

#include <wx/listbox.h>
#include <wx/panel.h>
#include <wx/textctrl.h>

// posted when an item in the ListBox is deleted
wxDECLARE_EVENT(myEVT_COMMAND_TRACKEEBOX_DELETED, wxCommandEvent);

// Events emitted by this class:
//    custom wxCommandEvent with Id myEVT_COMMAND_TRACKEEBOX_DELETED
//    wxCommandEvent with Id wxEVT_COMMAND_LISTBOX_SELECTED; event macro:
// EVT_LISTBOX(id, func)
//    wxCommand Event with Id wxEVT_COMMAND_TEXT_ENTER; event macro:
// EVT_TEXT_ENTER(id, func)
class TrackeeBox : public wxPanel
{
   public:

   TrackeeBox(wxWindow* parent, wxWindowID = wxID_ANY, const wxPoint& = wxDefaultPosition,
      const wxSize& = wxDefaultSize);

   void deleteSelection();

   void reset();

   wxString getStringSelection() const;

   private:

   // Processes wxEVT_COMMAND_TEXT_ENTER, posted by *textCtrl. Propagated up to the parent
   // window after the call. If an item is added to *listBox it will also be selected, but
   // no selection event will be triggered.
   void onEnter(wxCommandEvent&);

   // processes a wxEVT_COMMAND_LISTBOX_SELECTED; generated by *listBox
   //void onSelected(wxCommandEvent&);

   // Responds to a wxEVT_KEY_UP event emitted by the ListBox; deletes items for
   // wxKeyEvent keycode WXK_DELETE and posts myEVT_COMMAND_TRACKEEBOX_DELETED.
   void onKeyUp(wxKeyEvent&);

   // processes a wxEVT_CONTEXT_MENU
   void onContextMenu(wxContextMenuEvent&);

   wxBoxSizer* vBox;

   wxTextCtrl* textCtrl;
   wxListBox* listBox;
};

#endif //TRACKEE_BOX_H

// vim: tw=90 sw=3 et
