#ifndef TRACKEE_BOX_H
#define TRACKEE_BOX_H

#include <string>

#include <wx/listbox.h>
#include <wx/panel.h>
#include <wx/textctrl.h>

wxDECLARE_EVENT(myEVT_COMMAND_TRACKEEBOX_DELETED, wxCommandEvent); // posted when an item in the ListBox is deleted

// Events emitted by this class:
	//	custom wxCommandEvent with Id myEVT_COMMAND_TRACKEEBOX_DELETED
	//	wxCommandEvent with Id wxEVT_COMMAND_LISTBOX_SELECTED; event macro: EVT_LISTBOX(id, func)
	//	wxCommand Event with Id wxEVT_COMMAND_TEXT_ENTER; event macro: EVT_TEXT_ENTER(id, func)
class TrackeeBox : public wxPanel
{
	public:

	TrackeeBox(wxWindow* parent, wxWindowID = wxID_ANY, const wxPoint& = wxDefaultPosition,
		const wxSize& = wxDefaultSize);

	void deleteSelection();

	void reset();

	wxString getStringSelection()	const;

	private:

	// processes a wxEVT_COMMAND_TEXT_ENTER, posted by *textCtrl; propagated up to the parent window after the call;
	void onEnter(wxCommandEvent&); // if an item is added to *listBox it will also be selected, but no selection
	                               // event will be emitted

	//void onSelected(wxCommandEvent&); // processes a wxEVT_COMMAND_LISTBOX_SELECTED; generated by *listBox

	// responds to a wxEVT_KEY_UP event emitted by the ListBox; deletes items for wxKeyEvent keycode
	void onKeyUp(wxKeyEvent&); // WXK_DELETE and posts myEVT_COMMAND_TRACKEEBOX_DELETED

	wxBoxSizer* vBox;

	wxTextCtrl* textCtrl;
	wxListBox* listBox;
};

#endif //TRACKEE_BOX_H
